<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;

class StoreTourPackageRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true; // Authorization logic if needed
    }

    public function rules()
    {
        return [
            'title' => 'required|string|max:255',
            'slug' => 'required|string|max:255',
            'tour_includes' => 'required|string',
            'tour_not_includes' => 'required|string',
            'tour_type_id' => 'required|string',
            'minimum_age' => 'required|string',
            'transport_id' => 'required|string',
            'meal_id' => 'required|string',
            'accommodation_id' => 'required|string',
            'language_id' => 'required|string',
            'from_date' => 'required|string',
            'to_date' => 'required|string',
            'duration' => 'required|string|max:50',
            'group_size' => 'required|string',
            'accommodation' => 'required|string|max:100',
            'transportation' => 'required|string|max:100',
            'meals' => 'required|string|max:100',
            'fitness_level' => 'required|string|max:50',
            'min_age' => 'required|string',
            'guiding_method_id' => 'required|string',
            'guiding_method' => 'required|string|max:100',
            'language' => 'required|string|max:50',
            'travel_point_id' => 'required|string',
            'season_id' => 'required|string',
            'best_season' => 'required|string|max:100',
            'departure_from_id' => 'required|string',
            'departure_from' => 'required|string|max:50',
            'arrival_on_id' => 'required|string',
            'arrival_on' => 'required|string|max:50',
            'max_altitude' => 'required|string|max:50',
            'location' => 'required|string|max:255',
            'feature_image' => 'required|string|max:100',
            'thumbnail' => 'required|file|mimes:jpeg,png,jpg,gif,svg,pdf,doc,docx|max:10240',
            'gallery_images' => 'required|string',
            'video' => 'required|string|max:100',
            'video_url' => 'required|string|max:100',
            'feedback_logs' => 'required|string',
            'unit_price' => 'required|string',
            'discount_type' => 'required|string',
            'discount' => 'required|string',
            'discount_price' => 'required|string',
            'sale_price' => 'required|string',
            'sub_title' => 'required|string|max:255',
            'intro' => 'required|string',
            'highlight' => 'required|string',
            'attraction' => 'required|string',
            'location_image' => 'required|string|max:255',
            'trip_notes' => 'required|string',
            'faq' => 'required|string',
            'reviews' => 'required|string',
            'pickup_location' => 'required|string|max:255',
            'dropoff_location' => 'required|string|max:255',
            'pdf_url' => 'required|string|max:200',
            'is_popular_day_trips' => 'required|string',
            'is_tour_by_traveller_choise' => 'required|string',
            'is_featured' => 'required|string',
            'is_published' => 'required|string',
            'published_date' => 'required|string',
            'is_active' => 'required|string',
            'meta_title' => 'required|string|max:200',
            'meta_description' => 'required|string|max:500',
            'meta_keyword' => 'required|string|max:255',
            'canonical_url' => 'required|string|max:255',
            'meta_robots' => 'required|string|max:100',
            'meta_img' => 'required|string|max:255',
            'structured_data' => 'required|string',
            'og_title' => 'required|string|max:200',
            'og_description' => 'required|string|max:500',
            'og_image' => 'required|string|max:255',
            'twitter_title' => 'required|string|max:200',
            'twitter_description' => 'required|string|max:500',
            'twitter_image' => 'required|string|max:255',
            'created_by' => 'nullable|numeric',
            'created_at' => 'nullable|date',
            'deleted_at' => 'required|string',
        ];
    }

    public function messages()
    {
        return [
            'title.required' => 'The title field is required.',
            'title.string' => 'The title field must be a string.',
            'title.max' => 'The title field must not exceed 255 characters.',
            'slug.required' => 'The slug field is required.',
            'slug.string' => 'The slug field must be a string.',
            'slug.max' => 'The slug field must not exceed 255 characters.',
            'tour_includes.required' => 'The tour_includes field is required.',
            'tour_includes.string' => 'The tour_includes field must be a string.',
            'tour_not_includes.required' => 'The tour_not_includes field is required.',
            'tour_not_includes.string' => 'The tour_not_includes field must be a string.',
            'tour_type_id.required' => 'The tour_type_id field is required.',
            'tour_type_id.numeric' => 'The tour_type_id field must be a numeric.',
            'minimum_age.required' => 'The minimum_age field is required.',
            'minimum_age.numeric' => 'The minimum_age field must be a numeric.',
            'transport_id.required' => 'The transport_id field is required.',
            'transport_id.numeric' => 'The transport_id field must be a numeric.',
            'meal_id.required' => 'The meal_id field is required.',
            'meal_id.numeric' => 'The meal_id field must be a numeric.',
            'accommodation_id.required' => 'The accommodation_id field is required.',
            'accommodation_id.numeric' => 'The accommodation_id field must be a numeric.',
            'language_id.required' => 'The language_id field is required.',
            'language_id.numeric' => 'The language_id field must be a numeric.',
            'from_date.required' => 'The from_date field is required.',
            'from_date.string' => 'The from_date field must be a string.',
            'to_date.required' => 'The to_date field is required.',
            'to_date.string' => 'The to_date field must be a string.',
            'duration.required' => 'The duration field is required.',
            'duration.string' => 'The duration field must be a string.',
            'duration.max' => 'The duration field must not exceed 50 characters.',
            'group_size.required' => 'The group_size field is required.',
            'group_size.numeric' => 'The group_size field must be a numeric.',
            'accommodation.required' => 'The accommodation field is required.',
            'accommodation.string' => 'The accommodation field must be a string.',
            'accommodation.max' => 'The accommodation field must not exceed 100 characters.',
            'transportation.required' => 'The transportation field is required.',
            'transportation.string' => 'The transportation field must be a string.',
            'transportation.max' => 'The transportation field must not exceed 100 characters.',
            'meals.required' => 'The meals field is required.',
            'meals.string' => 'The meals field must be a string.',
            'meals.max' => 'The meals field must not exceed 100 characters.',
            'fitness_level.required' => 'The fitness_level field is required.',
            'fitness_level.string' => 'The fitness_level field must be a string.',
            'fitness_level.max' => 'The fitness_level field must not exceed 50 characters.',
            'min_age.required' => 'The min_age field is required.',
            'min_age.numeric' => 'The min_age field must be a numeric.',
            'guiding_method_id.required' => 'The guiding_method_id field is required.',
            'guiding_method_id.numeric' => 'The guiding_method_id field must be a numeric.',
            'guiding_method.required' => 'The guiding_method field is required.',
            'guiding_method.string' => 'The guiding_method field must be a string.',
            'guiding_method.max' => 'The guiding_method field must not exceed 100 characters.',
            'language.required' => 'The language field is required.',
            'language.string' => 'The language field must be a string.',
            'language.max' => 'The language field must not exceed 50 characters.',
            'travel_point_id.required' => 'The travel_point_id field is required.',
            'travel_point_id.numeric' => 'The travel_point_id field must be a numeric.',
            'season_id.required' => 'The season_id field is required.',
            'season_id.numeric' => 'The season_id field must be a numeric.',
            'best_season.required' => 'The best_season field is required.',
            'best_season.string' => 'The best_season field must be a string.',
            'best_season.max' => 'The best_season field must not exceed 100 characters.',
            'departure_from_id.required' => 'The departure_from_id field is required.',
            'departure_from_id.numeric' => 'The departure_from_id field must be a numeric.',
            'departure_from.required' => 'The departure_from field is required.',
            'departure_from.string' => 'The departure_from field must be a string.',
            'departure_from.max' => 'The departure_from field must not exceed 50 characters.',
            'arrival_on_id.required' => 'The arrival_on_id field is required.',
            'arrival_on_id.numeric' => 'The arrival_on_id field must be a numeric.',
            'arrival_on.required' => 'The arrival_on field is required.',
            'arrival_on.string' => 'The arrival_on field must be a string.',
            'arrival_on.max' => 'The arrival_on field must not exceed 50 characters.',
            'max_altitude.required' => 'The max_altitude field is required.',
            'max_altitude.string' => 'The max_altitude field must be a string.',
            'max_altitude.max' => 'The max_altitude field must not exceed 50 characters.',
            'location.required' => 'The location field is required.',
            'location.string' => 'The location field must be a string.',
            'location.max' => 'The location field must not exceed 255 characters.',
            'feature_image.required' => 'The feature_image field is required.',
            'feature_image.string' => 'The feature_image field must be a string.',
            'feature_image.max' => 'The feature_image field must not exceed 100 characters.',
            'thumbnail.required' => 'The thumbnail field is required.',
            'thumbnail.string' => 'The thumbnail field must be a string.',
            'thumbnail.max' => 'The thumbnail field must not exceed 100 characters.',
            'gallery_images.required' => 'The gallery_images field is required.',
            'gallery_images.string' => 'The gallery_images field must be a string.',
            'video.required' => 'The video field is required.',
            'video.string' => 'The video field must be a string.',
            'video.max' => 'The video field must not exceed 100 characters.',
            'video_url.required' => 'The video_url field is required.',
            'video_url.string' => 'The video_url field must be a string.',
            'video_url.max' => 'The video_url field must not exceed 100 characters.',
            'feedback_logs.required' => 'The feedback_logs field is required.',
            'feedback_logs.string' => 'The feedback_logs field must be a string.',
            'unit_price.required' => 'The unit_price field is required.',
            'unit_price.string' => 'The unit_price field must be a string.',
            'discount_type.required' => 'The discount_type field is required.',
            'discount_type.boolean' => 'The discount_type field must be a boolean.',
            'discount.required' => 'The discount field is required.',
            'discount.string' => 'The discount field must be a string.',
            'discount_price.required' => 'The discount_price field is required.',
            'discount_price.string' => 'The discount_price field must be a string.',
            'sale_price.required' => 'The sale_price field is required.',
            'sale_price.string' => 'The sale_price field must be a string.',
            'sub_title.required' => 'The sub_title field is required.',
            'sub_title.string' => 'The sub_title field must be a string.',
            'sub_title.max' => 'The sub_title field must not exceed 255 characters.',
            'intro.required' => 'The intro field is required.',
            'intro.string' => 'The intro field must be a string.',
            'highlight.required' => 'The highlight field is required.',
            'highlight.string' => 'The highlight field must be a string.',
            'attraction.required' => 'The attraction field is required.',
            'attraction.string' => 'The attraction field must be a string.',
            'location_image.required' => 'The location_image field is required.',
            'location_image.string' => 'The location_image field must be a string.',
            'location_image.max' => 'The location_image field must not exceed 255 characters.',
            'trip_notes.required' => 'The trip_notes field is required.',
            'trip_notes.string' => 'The trip_notes field must be a string.',
            'faq.required' => 'The faq field is required.',
            'faq.string' => 'The faq field must be a string.',
            'reviews.required' => 'The reviews field is required.',
            'reviews.string' => 'The reviews field must be a string.',
            'pickup_location.required' => 'The pickup_location field is required.',
            'pickup_location.string' => 'The pickup_location field must be a string.',
            'pickup_location.max' => 'The pickup_location field must not exceed 255 characters.',
            'dropoff_location.required' => 'The dropoff_location field is required.',
            'dropoff_location.string' => 'The dropoff_location field must be a string.',
            'dropoff_location.max' => 'The dropoff_location field must not exceed 255 characters.',
            'pdf_url.required' => 'The pdf_url field is required.',
            'pdf_url.string' => 'The pdf_url field must be a string.',
            'pdf_url.max' => 'The pdf_url field must not exceed 200 characters.',
            'is_popular_day_trips.required' => 'The is_popular_day_trips field is required.',
            'is_popular_day_trips.boolean' => 'The is_popular_day_trips field must be a boolean.',
            'is_tour_by_traveller_choise.required' => 'The is_tour_by_traveller_choise field is required.',
            'is_tour_by_traveller_choise.boolean' => 'The is_tour_by_traveller_choise field must be a boolean.',
            'is_featured.required' => 'The is_featured field is required.',
            'is_featured.boolean' => 'The is_featured field must be a boolean.',
            'is_published.required' => 'The is_published field is required.',
            'is_published.boolean' => 'The is_published field must be a boolean.',
            'published_date.required' => 'The published_date field is required.',
            'published_date.string' => 'The published_date field must be a string.',
            'is_active.required' => 'The is_active field is required.',
            'is_active.boolean' => 'The is_active field must be a boolean.',
            'meta_title.required' => 'The meta_title field is required.',
            'meta_title.string' => 'The meta_title field must be a string.',
            'meta_title.max' => 'The meta_title field must not exceed 200 characters.',
            'meta_description.required' => 'The meta_description field is required.',
            'meta_description.string' => 'The meta_description field must be a string.',
            'meta_description.max' => 'The meta_description field must not exceed 500 characters.',
            'meta_keyword.required' => 'The meta_keyword field is required.',
            'meta_keyword.string' => 'The meta_keyword field must be a string.',
            'meta_keyword.max' => 'The meta_keyword field must not exceed 255 characters.',
            'canonical_url.required' => 'The canonical_url field is required.',
            'canonical_url.string' => 'The canonical_url field must be a string.',
            'canonical_url.max' => 'The canonical_url field must not exceed 255 characters.',
            'meta_robots.required' => 'The meta_robots field is required.',
            'meta_robots.string' => 'The meta_robots field must be a string.',
            'meta_robots.max' => 'The meta_robots field must not exceed 100 characters.',
            'meta_img.required' => 'The meta_img field is required.',
            'meta_img.string' => 'The meta_img field must be a string.',
            'meta_img.max' => 'The meta_img field must not exceed 255 characters.',
            'structured_data.required' => 'The structured_data field is required.',
            'structured_data.string' => 'The structured_data field must be a string.',
            'og_title.required' => 'The og_title field is required.',
            'og_title.string' => 'The og_title field must be a string.',
            'og_title.max' => 'The og_title field must not exceed 200 characters.',
            'og_description.required' => 'The og_description field is required.',
            'og_description.string' => 'The og_description field must be a string.',
            'og_description.max' => 'The og_description field must not exceed 500 characters.',
            'og_image.required' => 'The og_image field is required.',
            'og_image.string' => 'The og_image field must be a string.',
            'og_image.max' => 'The og_image field must not exceed 255 characters.',
            'twitter_title.required' => 'The twitter_title field is required.',
            'twitter_title.string' => 'The twitter_title field must be a string.',
            'twitter_title.max' => 'The twitter_title field must not exceed 200 characters.',
            'twitter_description.required' => 'The twitter_description field is required.',
            'twitter_description.string' => 'The twitter_description field must be a string.',
            'twitter_description.max' => 'The twitter_description field must not exceed 500 characters.',
            'twitter_image.required' => 'The twitter_image field is required.',
            'twitter_image.string' => 'The twitter_image field must be a string.',
            'twitter_image.max' => 'The twitter_image field must not exceed 255 characters.',
            'created_by.required' => 'The created_by field is required.',
            'created_by.numeric' => 'The created_by field must be a numeric.',
            'deleted_at.required' => 'The deleted_at field is required.',
            'deleted_at.string' => 'The deleted_at field must be a string.',
        ];
    }
}
